### ISSUE TITLE
Introduce Ohara Volume (chapter 0)

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#4460]
We all love stateless services but there is no rule without an exception. Both of Zookeeper and Broker service plays as storage to Ohara and we can't, unfortunately, keep the data consistently. This issue is about to include the container volume to ohara object that users are able to configure the volume and then mount it on specify services. Those volumes are alive until users kill them manually. 

1. - [x] add volume support to ContainerClient (@chia7712) (#4532)
1. - [x] add volume support to K8sClient (@jackyoh ) (#4556)
1. - [ ] add Volume route (moved to #4621)
1. - [x] apply Volume to ZookeeperApi, BrokerApi, WorkerApi and StreamApi (#4629)
1. - [x] ContainerClient#container(String) and ContainerClient#volume(String) should return collection (#4540)
1. - [x] pass ContainerClient rather than K8sClient to Configurator (#4554)
1. - [x] add Volume support to collie (#4566)
1. - [x] move ClusterStatus from Configurator module to Agent module (#4557)
1. - [x] add ClusterState to both of ClusterInfo and ClusterStatus (#4562)
1. - [x] refactor TestCollie to remove stale test APIs (#4565)
1. - [ ] Added mount volume to create pod for the K8SClient and DockerClient (#4575 )
1. - [x] Added validate folder class for the remote node (#4648 )

**Comment by chia7712** [comment]
第一版的volume support目標是先能有基本的volume操作，因此有以下幾個限制:

1. 只支援local file system (其他如nfs, tmpFs等等都不支援)
1. 一個ohara volume可以對應多個節點，例如使用者可以宣告這個volume應該被"佈署"在n0, n1節點上，此設計是由於方便讓service和volume為一對一的關係
1. 如果volume的佈署範圍無法涵蓋service的佈署範圍的話，則會拋出錯誤
1. 不支援space limit的資源控管
1. 不支援顯示可用空間
1. volume的刪除"不會"跟著刪除對應目錄 (這部分仰賴使用者自行的linux操作) 
1. 一個正在被使用的volume無法被更新或刪除

*Create a Volumn*

```POST /v0/volumns```
```json
{
  "group": "group",
  "name": "name",
  "nodeNames": ["n0", "n1"],
  "path": "/tmp/aaa"
}
```

*Update a Volumn*

```PUT /v0/volumns/$name?gruop=$group```
```json
{
  "path": "/tmp/aaa2"
}
```

*Delete a Volumn*

```DELETE /v0/volumns/$name?gruop=$group```


*Get a Volumn*

```GET /v0/volumns/$name?gruop=$group```
```json
{
  "group": "group",
  "name": "name",
  "nodeNames": ["n0", "n1"],
  "path": "/tmp/aaa"
}
```

Definition會新增一個Reference為Volume，用來給作為目錄的key值設定，例如
```java
SettingDef.builder()
  .key(LOG_DIRS_KEY)
  .optional(Type.OBJECT_KEY)
  .reference(SettingDef.Reference.VOLUME)
  .build
```

@jackyoh @vitojeng 麻煩你們看一下上述的限制以及APIs，

**Comment by eechih** [comment]
@chia7712 沒有 Get all Volumns Api，漏掉了嗎？ 同一個 group 下的 path 是否要限制為 unique？

**Comment by chia7712** [comment]
> 沒有 Get all Volumns Api，漏掉了嗎？

漏掉了XD

> 同一個 group 下的 path 是否要限制為 unique？

你是指同一個group + name吧? 如果是的話，那的確要做檢查

> UI 如何知道一個 Volumn 被使用中？Get a Volumn Api 回傳的 data 沒有相關的訊息。

這是UI流程需要嗎? 現在我還沒列任何"runtime"的資訊，看UI流程需要哪些可以提出來討論

**Comment by eechih** [comment]
> 你是指同一個group + name吧? 如果是的話，那的確要做檢查

喔喔～ group + name 為 unique 應該是基本規則。不過，我問的是 path，因為在同一個 group 下有兩組 （path 相同, nodeNames 不同）的 Volumn ，使用者應該很容易混淆吧。

> 這是UI流程需要嗎?現在我還沒列任何"runtime"的資訊，看UI流程需要哪些可以提出來討論 

是的，UI 可以先阻擋使用者修改或刪除正在使用中的 Volumn

**Comment by chia7712** [comment]
> 因為在同一個 group 下有兩組 （path 相同, nodeNames 不同）的 Volumn ，使用者應該很容易混淆吧。我猜想使用者選擇 Volumn 時，應該會認 path 而不是 name。

我覺得讓path不能重複使用故事比較單純，使用者在指定volume的時候應該還是會認名字，畢竟path可能會很難閱讀

> 是的，UI 可以先阻擋使用者修改或刪除正在使用中的 Volumn

那就加上一個runtime資訊顯示被誰使用? 例如
```json
{
   "references": [
      {
         "group": "g",
         "name": "n",
         "kind": "zookeeper"
      }
    ] 
}
```

**Comment by jackyoh** [comment]
@chia7712 

1.那要限制在 node 建立資料夾的使用者權限為 root 嗎？ 因為 container 執行的 user 為 ohara, node 建立的 user 為 root，我不太確定是否會發生 permission denied 的問題
2. 當 volume 使用的資料夾路徑不存在我們要幫使用者建立還是要丟 exception?

**Comment by chia7712** [comment]
> 那要限制在 node 建立資料夾的使用者權限為 root 嗎？ 因為 container 執行的 user 為 ohara, node 建立的 user 為 root，我不太確定是否會發生 permission denied 的問題

Docker mode的話就是設定的使用者要有權限、k8s也是。現階段沒有權限就是拋錯

> 當 volume 使用的資料夾路徑不存在我們要幫使用者建立還是要丟 exception?

嘗試建立，否則拋錯

**Comment by vitojeng** [comment]
> 一個正在被使用的volume無法被更新或刪除

這是否意味著: 一個 service 擴充節點, 除了 service 本身的 definition 要修改外, 其對應的 volumn 也須要修改, 而且是必須的?(我們需要檢查?)

**Comment by vitojeng** [comment]
> volume path不可以重複

是否指不同的 volumn 之間, path 不可重覆的意思?

**Comment by vitojeng** [comment]
另外一個可能容易會有的情境:
由於不同的 node 配置的資源不一致, 例如 mount 的硬碟數量不同, 或是硬碟的容量不一樣.
這種情形下, 很有可能出現 volumn 裡在不同的 node 裡的 path "被迫" 無法一致.

不同時期買的硬體不盡相同, 這種不一致的情形很可能發生...

**Comment by chia7712** [comment]
> 這是否意味著: 一個 service 擴充節點, 除了 service 本身的 definition 要修改外, 其對應的 volumn 也須要修改, 而且是必須的?(我們需要檢查?)

擴充的部分會獨立成一組API，因為背後要做的動作比較適合由後端來處理而非前端

> 是否指不同的 volumn 之間, path 不可重覆的意思?

yep

> 討論: 另外一個可能容易會有的情境
由於不同的 node 配置的資源不一致, 例如 mount 的硬碟數量不同, 或是硬碟的容量不一樣.
這種情形下, 很有可能出現一個 volumn 裡在不同的 node 裡的 path "被迫" 無法一致.
不同時期買的硬體不盡相同, 我想這種不一致的情形很可能發生

以後才支援異質環境，否則無論是API或是UI都會有很大幅度的改動

**Comment by vitojeng** [comment]
>擴充的部分會獨立成一組API，因為背後要做的動作比較適合由後端來處理而非前端

酷!

> 以後才支援異質環境，否則無論是API或是UI都會有很大幅度的改動

了解~

**Comment by chia7712** [comment]
@jackyoh 歹勢 我剛剛注意到一些APIs的定義有些不恰當，我會很快發隻PR調整一下 :(

**Comment by jackyoh** [comment]
有，看到 PR 了。 

volumes 回傳的值改成 Seq[ContainerVolume] 了。

**Comment by chia7712** [comment]
@jackyoh 麻煩你有空先把k8s的實作補上，我會接著把它套用到route上面 感恩恩

**Comment by jackyoh** [comment]
OK, 我大概明天就可以開始實作了。

**Comment by jackyoh** [comment]
@chia7712
目前我把 K8S Volume 的部份 implement 完了 (volumeCreator, removeVolumes 和 volumes) 已經先開草稿的 PR 了 #4556  (我下午還會在看是否要補一些測試程式)。

目前我有遇到以下二個問題：
1. ContainerCreator#doCreate 是否要先接上 volume 的 mapping (像是 Docker Mode 的 docker run -v ${VOLUME_NAME}:${CONTAINER_PATH}), 還是要等到做 apply Volume on zookeeper service 再來實作 volume 的 mapping?


2. 關於 volume name 的部份，因為 k8s 的 persistent volume 是從整體性來看，因此如果 volume1 建立在 node1 ，之後 volume1 這個名稱就不能建立在 node2 會發生 already exists 的錯誤。但 Docker Mode 不會遇到此問題，因為直接在不同 node 建立相同的 volume name 不會有名稱衝到的問題。

因此我覺得在 volume name 的部份我們應該要做設計，就像是我們的 zk, bk 和 wk 服務的 container name 一樣。這樣才能解決關於 volume name 衝突的問題

**Comment by chia7712** [comment]
> ContainerCreator#doCreate 是否要先接上 volume 的 mapping (像是 Docker Mode 的 docker run -v ${VOLUME_NAME}:${CONTAINER_PATH}), 還是要等到做 apply Volume on zookeeper service 再來實作 volume 的 mapping?

這會在別隻pr

> 關於 volume name 的部份，因為 k8s 的 persistent volume 是從整體性來看，因此如果 volume1 建立在 node1 ，之後 volume1 這個名稱就不能建立在 node2 會發生 already exists 的錯誤。但 Docker Mode 不會遇到此問題，因為直接在不同 node 建立相同的 volume name 不會有名稱衝到的問題。

這個名稱管理由collie來處理

**Comment by jackyoh** [comment]
了解， Thank you.

**Comment by jackyoh** [comment]
目前在寫 ContainerClient mount volume 的測試程式時遇到 Node 資料夾權限的問題，有遇到以下二個狀況描述如下：

1.當 Node 的資料夾不存在時，在 ohara 預設的情況下會先建立一個資料夾，然後在 mount 到 container (zk, bk) 裡執行。 K8S 有提供當資料夾不存在時會建立資料夾的參數（DirectoryOrCreate），但建立出來的資料夾 own 和 group 通常都會是 root 因為相依於 kubelet service (k8s 執行的 service)
```
If nothing exists at the given path, an empty directory will be created there as needed with permission set to 0755, having the same group and ownership with Kubelet.
```
因為目前 ohara 執行服務的 container (zk和 bk) 使用者都為 ohara（UID=1000） mount 到 node 的資料夾 root (UID=0) 會發生 permission denied 的問題。


2.觀察到在 node 建立資料夾的 UID 要和執行 container (zk, bk 和 wk 服務) 的 UID 相同，例如 container 執行的 UID 是 1000, mount 到 node 的資料夾 own 也要是 1000，不然會發生 permission denied 的問題。

因此目前有想到一個解決方法，就是在 QA 裡，測試前先連到 IT 環境建立要 mount 的資料夾並修改 UID 的權限，測試程式就會取得設定參數的路徑然後 mount 到 container 裡執行測試的動作，最後跑完測試之後再把 QA 建立的資料夾刪除掉。

**Comment by chia7712** [comment]
@jackyoh 感謝提供的資訊

權限的部分考量我們目前還沒有要整合，因此目前比較適合的邏輯應該是使用者要事先準備好目錄給我們來mount(例如權限設定)，以及我們在建立ohara volume的時候要先確認權限是否可行 (例如目錄的使用者名稱一定要等於ohara，以及目錄是否存在)，簡單來說，在沒有整合權限的狀態下，我們不應該去做太多"猜測"的自動化

**Comment by jackyoh** [comment]
所以在 ContainerClient 測試程式的部份，應該要先在 IT 的 node 裡先建立資料夾，然後測試程式用 hard code 的方式指定 path 去檢查資料夾有沒有存在以及 own 是否為 ohara。

等做了權限管理之後再來整自動化的部份

**Comment by chia7712** [comment]
檢查的部分，k8s的APis能做到嗎？

**Comment by jackyoh** [comment]
K8S Api 做不到檢查 remote node 的資料夾有沒有存在以及資料夾的 own，我常常忘掉資料夾是 remote 的操作。

**Comment by chia7712** [comment]
> K8S Api 做不到檢查 remote node 的資料夾有沒有存在以及資料夾的 own，我常常忘掉資料夾是 remote 的操作。

或許利用ssh來做操作?

**Comment by jackyoh** [comment]
我這邊會先去研究看 K8S 的 plugin 看能不能做到建立資料夾的部份，如果最後沒辦法只能透過 ssh 的方式來建立資料夾。

**Comment by jackyoh** [comment]
我很像有找到在 k8s 的 node 建立資料夾的方法了，如下連結：
https://serverfault.com/questions/906083/how-to-mount-volume-with-specific-uid-in-kubernetes-pod

它的概念是在啟動 pod (container）之前會有一個 init container 的動作，mount 資料夾到 container 裡，之後調整資料夾的 own 權限，這樣 node 資料夾的 own 也會跟著修改。

目前有使用 ohara 的 zookeeper container 做個簡單的實驗，看起來 zookeeper container 可以順利存取 node 的資料夾，啟動 zookeeper pod 的 k8s 設定如下：
```
kind: Pod
metadata:
  labels:
    createdByOhara: k8s
  name: default-cnh754f214-zookeeper-3f0ea29
spec:
  initContainers:
  - name: volume-test-init
    image: busybox
    command: ["sh", "-c", "chown -R 1000:1000 /data"]
    volumeMounts:
    - name: volume1
      mountPath: /data
  containers:
  - args:
    - "--file"
    - "/home/ohara/default/data/myid=0"
    - "--file"
    - "/home/ohara/default/conf/zoo.cfg=initLimit=10,dataDir=/home/ohara/default/data,server.0=14-zookeeper-ae40098:37505:42415,syncLimit=5,tickTime=2000,clientPort=42813"
    - "--config"
    - "/home/ohara/default/conf/zoo.cfg"
    env:
    - name: JMXDISABLE
      value: 'true'
    - name: JVMFLAGS
      value: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.port=38259
        -Dcom.sun.management.jmxremote.rmi.port=38259 -Djava.rmi.server.hostname=ohara-k8s-master
        -Xmx1024M -Xms1024M"
    image: oharastream/zookeeper:0.10.0-SNAPSHOT
    volumeMounts:
    - name: volume1
      mountPath: "/home/ohara/default/data"
    imagePullPolicy: IfNotPresent
    name: ohara
    ports:
    - containerPort: 42813
      hostPort: 42813
    - containerPort: 37505
      hostPort: 37505
    - containerPort: 42415
      hostPort: 42415
    - containerPort: 38259
      hostPort: 38259
  hostAliases:
  - hostnames:
    - ohara-k8s-master
    ip: 192.168.1.211
  - hostnames:
    - ohara-k8s-slave00
    ip: 192.168.1.212
  hostname: 14-zookeeper-ae40098
  nodeSelector:
    kubernetes.io/hostname: ohara-k8s-master
  volumes:
  - name: volume1
    persistentVolumeClaim:
      claimName: volume1
  restartPolicy: Never
  subdomain: default
```

我明天還會繼續做進一步的測試，如果沒問題的話就會把以上的設定整入 ohara k8s json 設定的部份，並且繼續把 ContainerClient 的測試寫完。
