### ISSUE TITLE
研究 K8S 的 volume 功能

### ISSUE THREAD

**Issue by jackyoh** [oharastream/ohara#4538]
目前 ohara 的 zookeeper, broker 和 worker 都是使用 container 在建立服務，因此如果要長時間的保留資料就需要整合 volume 的功能，細節在 issue #4460。

在 K8S Client 的部份使用 hostPath 來做 container 做資料保留, 因為知道服務（zooker, broker 和 worker) 在哪台的 node 上執行, 所以使用 hostPath 是最簡單和方便的方式。

以下是一個簡單的 example, 有做 volume 功能的 pod:

```
apiVersion: v1
kind: Pod
metadata:
  name: test-volume
spec:
  containers:
  - name: test-volume
    image: nginx
    volumeMounts:
    - mountPath: /tmp/testVolume
      name: volume1
    imagePullPolicy: Always
  volumes:
  - name: volume1
    hostPath:
      path: /home/ohara/testVolume
      type: DirectoryOrCreate
``` 

在這個 sample 裡，hostPath 下面 path 是指執行 pod (container) 的 Node 的資料夾路徑, 當 node 不存在 /home/ohara/testVolume 的資料夾會做自動建立的動作。另外在執行 pod 時，會把 volume mount 到 test-volume container 的 /tmp/testVolume 路徑裡。
